// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://aifeyamngllcezkoxzxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZmV5YW1uZ2xsY2V6a294enh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MTY3MTEsImV4cCI6MjA3OTA5MjcxMX0.qHX9FBq4Yf-us_xuxsaPQ-d3YDbf0SW7WFS0rKtuWG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
